language: php

cache:
    directories:
        - $HOME/.cache/composer

services:
    - mysql

addons:
    mariadb: '10.1'

env:
    global:
        - CREATE_DB=false
        - DB_HOST=localhost
        - DB_PORT=3306
        - DB_USERNAME=root
        - DB_PASSWORD=""
        - DB_DATABASE=pimcore_test
        - PIMCORE_ENVIRONMENT=test
        - PIMCORE_TEST=1
        - PIMCORE_TEST_DB_DSN="mysql://root@localhost/pimcore_test"

install:
    - ./scripts/install.sh

script:
    - cd tmp
    - ./scripts/phpunit.sh
