services:
#    divante_pimcore_devkit.example:
#        class: Divante\PimcoreDevkitBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    PimcoreDevkitBundle\Service\InstallerService: ~
    PimcoreDevkitBundle\Service\WorkflowService: ~
    PimcoreDevkitBundle\Service\ClassDefinitionService: ~
