services:
    PimcoreDevkitBundle\Service\InstallerService: ~
    PimcoreDevkitBundle\Service\WorkflowService: ~
    PimcoreDevkitBundle\Service\ClassDefinitionService: ~
    PimcoreDevkitBundle\Service\CustomViewService: ~
    PimcoreDevkitBundle\Service\DataObjectService: ~
    PimcoreDevkitBundle\Service\KeyService: ~
    PimcoreDevkitBundle\Service\SystemSettings: ~
    PimcoreDevkitBundle\Service\UserService: ~
    PimcoreDevkitBundle\Service\WorkspaceService: ~
    PimcoreDevkitBundle\Service\DocTypeService: ~
    PimcoreDevkitBundle\Service\AssetService: ~
    PimcoreDevkitBundle\Service\ThumbnailConfigService: ~
    PimcoreDevkitBundle\Service\MigrationService: ~
    PimcoreDevkitBundle\Service\DocumentService: ~
    PimcoreDebkitBundle\Service\CustomLayoutService:
       arguments: ['@serializer']

    PimcoreDevkitBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
