services:
    PimcoreDevkitBundle\Service\InstallerService: ~
    PimcoreDevkitBundle\Service\WorkflowService: ~
    PimcoreDevkitBundle\Service\ClassDefinitionService: ~
    PimcoreDevkitBundle\Service\CustomViewService: ~
    PimcoreDevkitBundle\Service\DataObjectService: ~
    PimcoreDevkitBundle\Service\KeyService: ~
    PimcoreDevkitBundle\Service\SystemSettings: ~
    PimcoreDevkitBundle\Service\UserService: ~
    PimcoreDevkitBundle\Service\WorkspaceService: ~
    PimcoreDevkitBundle\Service\DocTypeService: ~
    PimcoreDevkitBundle\Service\AssetService: ~
    PimcoreDevkitBundle\Service\ThumbnailConfigService: ~
    PimcoreDevkitBundle\Service\MigrationService: ~
    PimcoreDevkitBundle\Service\DocumentService: ~
    PimcoreDebkitBundle\Service\CustomLayoutService:
       arguments: ['@serializer']

    pimcore_devkit.symfony_finder:
        class: Symfony\Component\Finder\Finder
        public: false

    PimcoreDevkitBundle\FileLocator\PimcoreClassLocator:
        class: PimcoreDevkitBundle\FileLocator\PimcoreClassLocator
        arguments: ['@Pimcore\Extension\Bundle\PimcoreBundleManager', '@pimcore_devkit.symfony_finder']

    PimcoreDevkitBundle\FileLocator\PimcoreBrickLocator:
        class: PimcoreDevkitBundle\FileLocator\PimcoreBrickLocator
        arguments: ['@Pimcore\Extension\Bundle\PimcoreBundleManager', '@pimcore_devkit.symfony_finder']

    PimcoreDevkitBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
