services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Symfony\Component\Finder\Finder: ~

    PimcoreDevkitBundle\FileLocator\PimcoreClassLocator:
        class: PimcoreDevkitBundle\FileLocator\PimcoreClassLocator
        arguments: ['@Pimcore\Extension\Bundle\PimcoreBundleManager', '@Symfony\Component\Finder\Finder']

    PimcoreDevkitBundle\FileLocator\PimcoreBrickLocator:
        class: PimcoreDevkitBundle\FileLocator\PimcoreBrickLocator
        arguments: ['@Pimcore\Extension\Bundle\PimcoreBundleManager', '@Symfony\Component\Finder\Finder']

    PimcoreDevkitBundle\FileLocator\PimcoreFieldcollectionLocator:
        class: PimcoreDevkitBundle\FileLocator\PimcoreFieldcollectionLocator
        arguments: ['@Pimcore\Extension\Bundle\PimcoreBundleManager', '@Symfony\Component\Finder\Finder']

    PimcoreDevkitBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']

    PimcoreDevkitBundle\Service\:
        resource: '../../Service'
        
    PimcoreDevkitBundle\Service\CustomLayoutService:
        arguments: ['@serializer']
        
    PimcoreDevkitBundle\Service\Wysiwyg\:
        resource: '../../Service/Wysiwyg'
